import { IBlogsHome } from "@/types/BlogsHome";



export const useRecentBlogs = () => {
    const exampleBlogs: IBlogsHome[] = [
        {
            _id: "ex1",
            title: "A Mansão Assombrada de Blackwood",
            description: "Uma investigação sobre os segredos sombrios da mansão abandonada que assombra a cidade há décadas.",
            thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&fit=crop",
            likes: [],
            status: true,
            avaliation: true,
            user: [],
            content: "",
            category: {
                _id: "",
                name: "Terror",
                thumbnail: "",
                rotateStyle: "0",
                marginStyle: "0",
                createdAt: "",
                updatedAt: "",
                __v: 0,
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            __v: 0,
        },
        {
            _id: "ex2",
            title: "Ritual de Sangue em Halloween",
            description: "As lendas urbanas sobre rituais antigos que acontecem nas noites de Halloween na floresta local.",
            thumbnail: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop",
            likes: [],
            status: true,
            avaliation: true,
            user: [],
            content: "",
            category: {
                _id: "",
                name: "Terror",
                thumbnail: "",
                rotateStyle: "0",
                marginStyle: "0",
                createdAt: "",
                updatedAt: "",
                __v: 0,
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            __v: 0,
        },
        {
            _id: "ex3",
            title: "O Espelho da Verdade",
            description: "Uma história sobre um espelho antigo que revela os segredos mais sombrios de quem ousa olhar.",
            thumbnail: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=300&fit=crop",
            likes: [],
            status: true,
            avaliation: true,
            user: [],
            content: "",
            category: {
                _id: "",
                name: "Terror",
                thumbnail: "",
                rotateStyle: "0",
                marginStyle: "0",
                createdAt: "",
                updatedAt: "",
                __v: 0,
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            __v: 0,
        },
        {
            _id: "ex4",
            title: "Sussurros na Escuridão",
            description: "Os habitantes do vilarejo relatam ouvir vozes sussurrantes vindas da caverna abandonada nas montanhas.",
            thumbnail: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=400&h=300&fit=crop",
            likes: [],
            status: true,
            avaliation: true,
            user: [],
            content: "",
            category: {
                _id: "",
                name: "Terror",
                thumbnail: "",
                rotateStyle: "0",
                marginStyle: "0",
                createdAt: "",
                updatedAt: "",
                __v: 0,
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            __v: 0,
        },
        {
            _id: "ex5",
            title: "A Boneca Amaldiçoada",
            description: "Uma boneca antiga encontrada em um antiquário possui poderes sobrenaturais que aterrorizam seus donos.",
            thumbnail: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=300&fit=crop",
            likes: [],
            status: true,
            avaliation: true,
            user: [],
            content: "",
            category: {
                _id: "",
                name: "Terror",
                thumbnail: "",
                rotateStyle: "0",
                marginStyle: "0",
                createdAt: "",
                updatedAt: "",
                __v: 0,
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            __v: 0,
        },
        {
            _id: "ex6",
            title: "Cemitério dos Esquecidos",
            description: "Explorando o antigo cemitério onde as almas não conseguem descansar em paz há mais de um século.",
            thumbnail: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=300&fit=crop",
            likes: [],
            status: true,
            avaliation: true,
            user: [],
            content: "",
            category: {
                _id: "",
                name: "Terror",
                thumbnail: "",
                rotateStyle: "0",
                marginStyle: "0",
                createdAt: "",
                updatedAt: "",
                __v: 0,
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            __v: 0,
        },
        {
            _id: "ex7",
            title: "O Último Telefone Público",
            description: "As chamadas que nunca deveriam ter sido feitas através de um telefone público abandonado na estrada.",
            thumbnail: "https://images.unsplash.com/photo-1519567339-0d30a8c8b5c1?w=400&h=300&fit=crop",
            likes: [],
            status: true,
            avaliation: true,
            user: [],
            content: "",
            category: {
                _id: "",
                name: "Terror",
                thumbnail: "",
                rotateStyle: "0",
                marginStyle: "0",
                createdAt: "",
                updatedAt: "",
                __v: 0,
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            __v: 0,
        },
        {
            _id: "ex8",
            title: "Sombra na Janela",
            description: "Um observador silencioso aparece todas as noites na janela da casa vazia da rua principal.",
            thumbnail: "https://images.unsplash.com/photo-1494597564530-871f2b93ac55?w=400&h=300&fit=crop",
            likes: [],
            status: true,
            avaliation: true,
            user: [],
            content: "",
            category: {
                _id: "",
                name: "Terror",
                thumbnail: "",
                rotateStyle: "0",
                marginStyle: "0",
                createdAt: "",
                updatedAt: "",
                __v: 0,
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            __v: 0,
        },
        {
            _id: "ex9",
            title: "A Serenata do Medo",
            description: "Uma música antiga que, quando tocada, traz consigo entidades sombrias do passado.",
            thumbnail: "https://images.unsplash.com/photo-1478720568477-1520d4b1139e?w=400&h=300&fit=crop",
            likes: [],
            status: true,
            avaliation: true,
            user: [],
            content: "",
            category: {
                _id: "",
                name: "Terror",
                thumbnail: "",
                rotateStyle: "0",
                marginStyle: "0",
                createdAt: "",
                updatedAt: "",
                __v: 0,
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            __v: 0,
        },
        {
            _id: "ex10",
            title: "O Passageiro Fantasma",
            description: "Relatos de motoristas que pegaram carona com um passageiro que desapareceu misteriosamente.",
            thumbnail: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=400&h=300&fit=crop",
            likes: [],
            status: true,
            avaliation: true,
            user: [],
            content: "",
            category: {
                _id: "",
                name: "Terror",
                thumbnail: "",
                rotateStyle: "0",
                marginStyle: "0",
                createdAt: "",
                updatedAt: "",
                __v: 0,
            },
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            __v: 0,
        },
    ];

    const nextBlog = () => {
        const nextButton = document.getElementById("next-blog");
        nextButton?.click();
      };
    
      const prevBlog = () => {
        const prevButton = document.getElementById("previous-blog");
        prevButton?.click();
      };
    


    return { exampleBlogs, nextBlog, prevBlog };
}